### ISSUE TITLE
请问我要识别英文文本应该如何设置呢？

### ISSUE THREAD

**Issue by iPengXPro** [CoireLen/CnocrCpp#2]
![image](https://user-images.githubusercontent.com/102793417/200125582-8d278b0d-f368-45b2-bf61-4b6707a36e00.png)
像这张图这样具有多行的英文文本，代码应该如何更改呢？我用python的cnocr可以识别，但是通过这个c++工程没有得出结果。

**Comment by CoireLen** [comment]
修改modle.h中的模型名称 ，下载python cnocr的英文模型放到同一目录下。
理论上因该就可以。
预计下周更新切换识别语言/模型

**Comment by iPengXPro** [comment]
您的邮件已收到，谢谢！

**Comment by iPengXPro** [comment]
![image](https://user-images.githubusercontent.com/102793417/200154095-6b3af1f7-5e21-4443-9937-19bd411c033e.png)
研究了一下源代码，黑底白字图片对调为白底黑字这段代码需要改一下，cnocr.cpp中的这一段改为 if (cv::sum(outimg.col(0))[0]/255 < 145)  这样就可以了。

**Comment by iPengXPro** [comment]
> 修改modle.h中的模型名称 ，下载python cnocr的英文模型放到同一目录下。 理论上因该就可以。 预计下周更新切换识别语言/模型

按您说的，我下载了en_PP-OCRv3_rec_infer.onnx，调用确报错了，请问这有什么解法吗？或者等您下周更新看看
![image](https://user-images.githubusercontent.com/102793417/200174762-ac08f153-c260-4e0d-bbb5-7dc2c25fdcc5.png)

**Comment by CoireLen** [comment]
写着写着就发现这两模型输入输出格式不一样,预处理,输出处理大部分都得重写,人麻了

**Comment by CoireLen** [comment]
已经整完了。
